### ISSUE TITLE
File configuration

### ISSUE THREAD

**Issue by brettlangdon** [DataDog/riot#15]
Right now only programmatic configuration is supported by this POC.

Should we aim to keep it as programmatic configuration only or offer yaml/json/toml/ini?

```yaml
#riot.yaml

# TODO: Global config options?

suites:
  - name: tracer
    command: pytest tests/test_tracer.py
    cases:
      - pys: [2.7, 3.5, 3.6, 3.7, 3.8,]
        pkgs:
          - name: msgpack
            versions: [null, "==0.5.0", ">=0.5,<0.6", ">=0.6.0,<1.0", "latest"]
```

This maps fairly closely to the programmatic example we have today.

If we want to keep programmatic/python config option, how should we approach? `riotfile.py`, `riot_config.py`, etc?
